---
- name: Sample Playbook run with localhost
  hosts: localhost
  connection: local

  tasks:
  - name: Say Hello
    debug:
      msg: "This is a Hello from Ansible"
  - name: Say Hello 2
    debug:
      msg: "This is a 2nd Hello from Ansible"